---
Name: socialselement
---
RyanPotter\SilverStripeColorField\Forms\ColorField:
  colors:
    - '#003087'
    - '#0077c8'
    - '#008893'
    - '#BBDEFB'
    - '#FFFFFF'
    - '#FF4081'
    - '#212121'
    - '#727272'
    
NourAlmasrieh\SocialsElement:
  #Defines all Layouts
  Layouts:
    Slides:
      #id of layout needs to be the same as the key of this layout
      #id defines also the name for the special template
      id: 'Slides'
      # enable / disable this layout
      enabled: true
      # title of this layout. Will be used to identify this in the cms
      title: 'Slides'
      # path to Image which will be used in the cms
      imgPath: 'client/images/SocialwallSlides.jpg'
      # define all fields available in the cms for this layout
      FieldsVisibleElement:
        BackgroundColor: false
        SubTile: true
        ButtonCaption: true
        ExternalLink: true
        Content: true
        ShowOnLimitPosts: true
        ShowOnAllSocialsPost: true
        ShowOnFacebook: true
        ShowOnInstagram: true
        LinkedPageID: true
    Cards:
      #id of layout needs to be the same as the key of this layout
      #id defines also the name for the special template
      id: 'Cards'
      # enable / disable this layout
      enabled: true
      # title of this layout. Will be used to identify this in the cms
      title: 'Cards'
      # path to Image which will be used in the cms
      imgPath: 'client/images/SocialwallCards.jpg'
  # define all fields available in LinkedPage Object for this layout
      FieldsVisibleElement:
        BackgroundColor: false
        SubTile: true
        ButtonCaption: true
        ExternalLink: true
        Content: true
        ShowOnLimitPosts: true
        ShowOnAllSocialsPost: true
        ShowOnFacebook: true
        ShowOnInstagram: true
        LinkedPageID: true
  # settings for some fields
  FieldSettings:
      # height and width of the layout-select images in cms
      ImageHeight: 100
      ImageWidth: 195
      # description to the layout-select in the cms
      FieldDescription: 'Nach der Auswahl zuerst speichern.'